//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingRejse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunder
    {
        public int Kunde_ID { get; set; }
        public string Kunde_Navn { get; set; }
        public string Kunde_Adresse { get; set; }
        public Nullable<int> Kunde_Telefon { get; set; }
    }
}
