//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingRejse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejser
    {
        public int Rejse_ID { get; set; }
        public string Rejse_Titel { get; set; }
        public string Rejse_By { get; set; }
        public Nullable<System.DateTime> Rejse_Stardato { get; set; }
        public Nullable<System.DateTime> Rejse_Slutdato { get; set; }
        public Nullable<int> Rejse_Pris { get; set; }
        public Nullable<int> Rejse_MaxAntal { get; set; }
        public string Rejse_Beskrivelse { get; set; }
    }
}
